spring:
  application:
    name: web-api-client
  #если не указать здесь профиль, тогда будет выброшен
  # exception во время сопоставления свойств данного файла
  profiles: dev

random:
  joke:
    api:
      url: https://official-joke-api.appspot.com/random_joke

---

spring:
  profiles: dev, stage



feign:
  client:
    config:
      random-api:
        connect-timeout: 2000
        read-timeout: 4000
        loggerLevel: full

random:
  joke:
    api:
      url: 'https://official-joke-api.appspot.com/random_joke'

---

spring:
  profiles: prod

feign:
  client:
    config:
      randomjokeapi:
        connect-timeout: 1000
        read-timeout: 2000

random:
  joke:
    api:
      url: https://official-joke-api.appspot.com/random_joke
