event:
  starter:
    enabled: true
    listener:
      enabled-events:
        - kafka-stream

#event:
#  starter:
#    enabled: true
#    listener:
#      enabled-events:
#        - foo
#        - bar

